services: # Defines containers 

  frontend: 
    build: 
      context: frontend 
    ports: 
      - "5173:5173"
    depends_on: 
      - backend
  backend: 
      build: # Builds app image from dockerfile 
        context: backend 
      ports: 
        - "4000:3000"
      env_file: 
        - ./backend/.env # Load all envir from backend folder 
      depends_on: # Ensures mongo starts before express app 
      - mongo 


  mongo: # Mongodb service 
    image: mongo 
    container_name: mongodb_container 
    ports: 
    - "27017:27017"
    volumes: 
    - mongo_data:/data/db 

volumes: # Docker automatically creates volume 
  mongo_data: 
